### PR TITLE
Fix frequency_string_short and its usage

### PR DESCRIPTION
**Pull request by wutje**
When showing multiple markers there where two issues:
- The frequency shown for 1-9Mhz did not have the MHz string appended. (>=10Mhz did)
- Above ~2.1 Ghz it showed negative values due to frequency being stored in int32_t

### CODE REVIEW

**Comment by douardda** [comment]
why changing the frequency_string_short() signature to make it return an int? Is this returned values used / planned to be used somewhere ?

**Comment by wutje** [comment]
Yes, I am working on code that uses this same function to print the current frequency on recall buttons. That is how I found this bug.
Printing frequency with suffix can be hard and I rather reuse code then invent it again. But for my code to work I need the result of the snprintf.

**Comment by DiSlord** [comment]
See NanoVNA chprintf.c file for print frequence need only use "%q" and also support any formatting
For print value vs suffix like 0.0001 use "%F" and get 100u
Possible format "%+5.2F" for example and other printf formats

**Comment by douardda** [comment]
> Yes, I am working on code that uses this same function to print the current frequency on recall buttons. That is how I found this bug.
> Printing frequency with suffix can be hard and I rather reuse code then invent it again. But for my code to work I need the result of the snprintf.

Ok then this should be explained in the commit message IMHO (or be part of a dedicated commit).

**Comment by wutje** [comment]
@douardda I changed the code. It no longer returns the amount of characters printed. It is better take small steps. My other code is obsolete now due to @DiSlord great work on the GUI.
@DiSlord https://github.com/gabriel-tenma-white/mculib/blob/master/printf.cpp does not have %q?

**Comment by wutje** [comment]
Can this please be merged? It came up again as #40 .
Measuring a 2400 (Wifi, Bluetooth etc) filter is nearly impossible.
Is there anything I can or need to do so this can be merged?

**Comment by gabriel-tenma-white** [comment]
Sorry, thought this was already included in another PR. It's merged now.

**Comment by wutje** [comment]
Great! Thank you so much for the quick response.

**Comment by DG9BFC** [comment]
when can we expect a new release ?? i am no programer (just a user) so i have no idea how to compile a fw ... (i can upload a new one ... thats easy) ... 
i own TWO saa2 ... one with small and one with big display (4 inch and n sockets) so best would be compile both versions and release them (like we have seen some months ago)
THANK YOU dg9bfc sigi

**Comment by douardda** [comment]
> when can we expect a new release ?? i am no programer (just a user) so i have no idea how to compile a fw ... (i can upload a new one ... thats easy) ...
> i own TWO saa2 ... one with small and one with big display (4 inch and n sockets) so best would be compile both versions and release them (like we have seen some months ago)
> THANK YOU dg9bfc sigi

indeed, I've opened an issue for this #41

**Comment by douardda** [comment]
@DG9BFC I've compiled the current master (rev e017aab5) and put them here https://github.com/douardda/NanoVNA-V2-firmware/releases/tag/20200905

I've only tested the 2.8" (ili9341) version since I do not have a 4" display yet (should arrive in a few days hopefully).

Hope this helps.

**Comment by DG9BFC** [comment]
tested on small and big screen ... seems to work fine (both fw versions tested!! ... small and big screen!!)
so i think you can close issue 41 :-)
thank you

**Comment by lzqgdt** [comment]
tested on big screen ,no problem .

**Pull request merged**
